-- require("core.plugins_config.gruvbox")
require("core.plugins_config.lualine")
require("core.plugins_config.nvim-tree")
require("core.plugins_config.telescope")
require("core.plugins_config.lsp_config")
require("core.plugins_config.treesitter")
require("core.plugins_config.completions")
-- require("core.plugins_config.colorizer")
require("core.plugins_config.luasnip")
-- require("core.plugins_config.hardtime")
-- require("core.plugins_config.dap")
-- require("core.plugins_config.clangd")
-- require("core.plugins_config.debug")
require("core.plugins_config.toggleterm")
require("core.plugins_config.blankline")
-- require("core.plugins_config.cokeline")
-- require("core.plugins_config.nvim-web-devicons")
-- require("core.plugins_config.vimtex")
